# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.Author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.Paper')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='bids',
            field=models.ManyToManyField(through='bidding.Bid', to='bidding.Paper'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set([('author', 'paper', 'score')]),
        ),
    ]
