# Generated by Django 2.1.3 on 2019-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='affiliation',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
