# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_auto_20171109_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
