# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_bid_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='submitter',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set([('author', 'paper')]),
        ),
    ]
