# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auto_20171110_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='volunteer',
            field=models.BooleanField(default=True),
        ),
    ]
